[package]
name = "freshmint-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-multipart = "0.3"
actix-web = "3"
futures = "0.3.5"
image = "0.23.14"
serde = "1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
actix-rt = "1"
